version: "3.8"
services:
  users:
    build: ./users
    environment:
      PORT: '8080'
      URL_MONGODB: 'mongodb://mongo1:27017'
    ports:
      - "8080:8080"
    networks:
      - lan
    depends_on:
      - mongo1
  mongo1:
    image: mongo
    networks:
      - lan
    volumes:
      - vol1:/data/db

  tweets:
    build: ./tweets
    environment:
      PORT: '8081'
      URL_MONGODB: 'mongodb://mongo2:27017'
    ports:
      - "8081:8081"
    networks:
      - lan
    depends_on:
      - users
      - mongo2
  mongo2:
    image: mongo
    networks:
      - lan
    volumes:
      - vol2:/data/db
volumes:
  vol1:
  vol2:
networks:
 lan: